config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  resources :containers do
    member do
      post 'start'
      post 'stop'
      get 'logs'
      get 'stats'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/container.rb
class Container < ApplicationRecord
end

app/models/container_form.rb
# app/forms/container_form.rb
class ContainerForm
  include ActiveModel::Model

  attr_accessor :image, :name, :exposed_ports, :port_bindings, :always_pull

  # Validations
  validates :image, presence: true
  validate :name_must_be_hyphenated

  private
  def name_must_be_hyphenated
    unless name.match?(/\A[a-z0-9]+(-[a-z0-9]+)*\z/i)
      errors.add(:name, 'must contain only letters, numbers, and hyphens with no consecutive hyphens')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_docker_info
  private

  def set_docker_info
    @info = Docker.info
  rescue Docker::Error::DockerError => e
    @error = "Failed to connect to Docker daemon #{e.message}"
  end
end

app/controllers/containers_controller.rb
require 'docker'

class ContainersController < ApplicationController
  include ContainersHelper
  before_action :set_docker_url
  before_action :set_container, only: %i[ show edit update destroy logs start stop stats ]

  # GET /containers or /containers.json
  def index
    @containers = Docker::Container.all(all: true)
  rescue Docker::Error::DockerError => e
    @error = "Failed to connect to Docker daemon #{e.message}"
  end

  # GET /containers/1 or /containers/1.json
  def show
  end

  # Start container
  def start
    @container.start
    redirect_to containers_url, notice: "Container was succesfully started."
  rescue Docker::Error::DockerError => e
    redirect_to containers_url, alert: "Failed to start container: #{e.message}"
  end

  # Stop container
  def stop
    @container.stop
    redirect_to containers_url, notice: "Container was successfully stopped."
  rescue Docker::Error::DockerError => e
    redirect_to containers_url, alert: "Failed to stop container: #{e.message}"
  end

  # Container logs
  def logs
    log_entries = []
    include_stderr = params[:log_level] == 'advanced'
    
    @container.streaming_logs(stdout: true, stderr: include_stderr) do |stream, chunk|
      prefix = stream == :stdout ? "stdout" : "stderr"
      log_entries << "#{prefix}: #{chunk}" if include_stderr || stream == :stdout
    end

    @logs = log_entries
  end

  # Container stats (Non-Streaming)
  def stats
    stats_data = @container.stats(api: {stream: false})
    @container_stats = stats_data
  end

  # GET /containers/new
  def new
    @container_form = ContainerForm.new
    Rails.logger.debug "@container_form: #{@container_form.inspect}"
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers or /containers.json
  def create
    @container_form = ContainerForm.new(container_params)
  
    if @container_form.valid?
      docker_params = create_container_params(params)
  
      always_pull = ActiveModel::Type::Boolean.new.cast(@container_form.always_pull)
      if always_pull || !image_exists_locally?(docker_params['Image'])
        unless pull_image(docker_params['Image'])
          flash.now[:alert] = "Failed to pull the specified image. Please check the image name and try again."
          render :new, status: :unprocessable_entity and return
        end
      end

      @docker_container = Docker::Container.create(docker_params)

      if @docker_container.id.present?
        StartDockerContainerJob.perform_later(@docker_container.id)
        redirect_to containers_url, notice: "Container was successfully created."
      else
        # Handle the case where the Docker container does not provide an ID
        flash[:alert] = "Container creation failed for an unknown reason."
        render :new, status: :unprocessable_entity
      end
    else
      # This block is reached if the form validation fails
      render :new, status: :unprocessable_entity
    end
  end
  
  

  # PATCH/PUT /containers/1 or /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to container_url(@container), notice: "Container was successfully updated." }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1 or /containers/1.json
  def destroy
    @container.destroy!

    respond_to do |format|
      format.html { redirect_to containers_url, notice: "Container was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_docker_url
      if ENV['INSIDE_DOCKER'].present?
        Docker.url = 'unix://var/run/docker.sock'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Docker::Container.get(params[:id])
    rescue Docker::Error::DockerError => e
      @error = "Failed to get container #{e.message}"
    end

    # Only allow a list of trusted parameters through.
    def container_params
      params.require(:container_form).permit(:name, :image, :exposed_ports, :port_bindings, :always_pull)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # def index
  #   @info = Docker.info
  # rescue Docker::Error::DockerError => e
  #   @error = "Failed to connect to Docker daemon #{e.message}"
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
  def humanize_bytes(bytes)
    units = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB']
    return '0 Bytes' if bytes.to_i <= 0
    i = (Math.log(bytes) / Math.log(1024)).floor
    sprintf("%.2f %s", bytes.to_f / (1024 ** i), units[i])
  end

  def create_container_params(params)
    container_params = params[:container_form] || {}
    puts "Container Parameters: #{container_params}"
  
    filtered_params = container_params.reject { |key, value| value.blank? }
    puts "Filtered Parameters: #{filtered_params}"
  
    allowed_keys = ['Image', 'name', 'ExposedPorts', 'PortBindings']
    docker_options = {}
  
    filtered_params.each do |key, value|
      docker_key = key == 'name' ? 'name' : key.camelize
  
      if allowed_keys.include?(docker_key)
        case docker_key
        when 'ExposedPorts'
          # Only handling TCP
          port_with_protocol = "#{value}/tcp"
          docker_options['ExposedPorts'] = { port_with_protocol => {} }
        when 'PortBindings'
          # Only handling TCP & using filtered params port which is why it's not camelized.
          internal_port_with_protocol = "#{filtered_params['exposed_ports']}/tcp"
          external_port = "#{value}"
          docker_options['HostConfig'] ||= {}
          docker_options['HostConfig']['PortBindings'] = { internal_port_with_protocol => [{ 'HostPort' => external_port }] }
        else
          docker_options[docker_key] = value
        end
      end
    end
  
    puts "Docker Options: #{docker_options}"
    docker_options
  end
  

  def image_exists_locally?(image_name)
    Docker::Image.exist?(image_name)
  rescue Docker::Error::DockerError => e
    puts "Error checking if image exists locally: #{e.message}"
    false
  end

  def pull_image(image_name)
    Docker::Image.create('fromImage' => image_name)
    puts "Image pulled successfully: #{image_name}"
    true
  rescue Docker::Error::DockerError => e
    puts "Error pulling image: #{e.message}"
    false
  end

  def handle_image_pull(image_name, always_pull)
    if always_pull || !image_exists_locally?(image_name)
      pull_image(image_name)
    else
      puts "Using local image: #{image_name}"
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/containers/_container.html.erb
<div id="<%= dom_id container %>">
  <p>
    <strong>Name:</strong>
    <%= container.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= container.status %>
  </p>

</div>

app/views/containers/_form.html.erb
<div class="ml-64 p-10">
  <%= form_with(model: container_form, url: containers_path, local: true, class: "w-full max-w-lg") do |form| %>
    <% flash.each do |type, message| %>
      <div class="<%= type %>"><%= message %></div>
    <% end %>
    <% if container_form.errors.any? %>
      <div class="mb-6 p-4 bg-red-100 border border-red-400 text-red-700">
        <h2><%= pluralize(container_form.errors.count, "error") %> prohibited this container from being saved:</h2>

        <ul>
          <% container_form.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= form.label :image, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field :image, class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", placeholder: "Docker Image" %>
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= form.label :name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field :name, class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", placeholder: "Container Name" %>
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= form.label :container_port, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field :exposed_ports, class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", placeholder: "Container Port" %>
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= form.label :external_port, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <%= form.text_field :port_bindings, class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", placeholder: "External Port" %>
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full px-3">
        <%= form.label :always_pull, "Always Pull Image", class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
        <div class="mt-2">
          <%= radio_button_tag 'container_form[always_pull]', 'true', false, class: "mr-2" %>
          <%= label_tag 'container_form_always_pull_true', 'On', class: "mr-4" %>
          <%= radio_button_tag 'container_form[always_pull]', 'false', true, class: "mr-2" %>
          <%= label_tag 'container_form_always_pull_false', 'Off' %>
        </div>
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mt-6">
      <div class="w-full px-3">
        <%= form.submit "Deploy Container", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    </div>
  <% end %>
</div>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render "form", container: @container %>

<br>

<div>
  <%= link_to "Show this container", @container %> |
  <%= link_to "Back to containers", containers_path %>
</div>

app/views/containers/index.html.erb
<p class="text-green-500"><%= notice %></p>

<div class="ml-64 p-10">
  <div class="flex justify-center items-center">
    <% if @error %>
      <p class="text-red-500">Error: <%= @error %></p>
    <% else %>
      <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="py-3 px-6">ID</th>
              <th scope="col" class="py-3 px-6">Name</th>
              <th scope="col" class="py-3 px-6">Status</th>
              <th scope="col" class="py-3 px-6">Actions</th>
              <th scope="col" class="py-3 px-6">Logs/Debug</th>
              <th scope="col" class="py-3 px-6">Stats</th>
            </tr>
          </thead>

          <tbody>
            <% @containers.each do |container| %>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <td class="py-4 px-6"><%= link_to container.json['Id'][0..12].., container_path(container.json["Id"]), class: "text-blue-600 dark:text-blue-500 hover:underline"%></td>
                <td class="py-4 px-6"> <%= container.json['Name'].sub(/^\//, '') %></td>
                <td class="py-4 px-6"><%= container.info['State'] %></td>
                <td class="py-4 px-6">
                  <div class="flex items-center space-x 4">
                    <%= button_to 'Start', start_container_path(container.json['Id']), method: :post, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                    <%= button_to 'Stop', stop_container_path(container.json['Id']), method: :post, class: "font-medium text-red-600 dark:text-red-500 hover:underline ml-4" %>
                  </div>
                </td>
                <td class="py-4 px-6">
                  <div class="flex items-center space-x 4">
                    <%= link_to logs_container_path(container.json['Id'], log_level: 'basic') do %>
                      <%= image_tag 'log-file.png', alt: 'Basic Logs' %>
                    <% end %>
                    <%= link_to logs_container_path(container.json['Id'], log_level: 'advanced') do %>
                      <%= image_tag 'debugging.png', alt: 'Advanced Logs' %>
                    <% end %>
                  </div>
                </td>
                <td class="py-4 px-6">
                  <%= link_to stats_container_path(container.json['Id']) do %>
                    <%= image_tag 'dashboard.png', alt: 'Stats' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>
<% end %>

app/views/containers/logs.html.erb
<div class="ml-64 p-10">
  <div class="flex justify-center items-center mt-6">
    <div class="w-full max-w-4xl overflow-x-auto relative shadow-md sm:rounded-lg bg-white dark:bg-gray-800 p-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900 dark:text-white mb-4">Container Logs</h3>
      <div class="max-h-96 overflow-y-auto bg-gray-50 dark:bg-gray-900 p-4 rounded-lg">
        <ul class="list-disc space-y-2 pl-5">
          <% @logs.each do |log_entry| %>
            <li class="text-sm text-gray-500 dark:text-gray-400 font-mono">
              <%= log_entry %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/containers/new.html.erb
<div class="ml-64 p-10">
<h1>New container</h1>

<%= render "form", container_form: @container_form %>

<br>

<div>
  <%= link_to "Back to containers", containers_path %>
</div>
</div>

app/views/containers/show.html.erb
<div class="ml-64 p-8">
  <p class="text-green-500"><%= notice %></p>

  <h1 class="text-3xl font-bold underline mb-4">Container Info</h1>

  <% if @error %>
    <p class="text-red-500">Error: <%= @error %></p>
  <% else %>
    <div class="space-y-2">
      <p><strong>ID:</strong> <%= @container.json['Id'] %></p>
      <p><strong>Status:</strong> <%= @container.json['State']['Status'] %></p>
      <p><strong>OOM Killed:</strong> <%= @container.json['State']['OOMKilled'] ? 'Yes' : 'No' %></p>
      <p><strong>Exit Code:</strong> <%= @container.json['State']['ExitCode'] %></p>
      <p><strong>Error:</strong> <%= @container.json['State']['Error'].present? ? @container.json['State']['Error'] : 'None' %></p>
      <p><strong>Image:</strong> <%= @container.json['Image'] %></p>
      <p><strong>Name:</strong> <%= @container.json['Name'].sub(/^\//, '') %></p>
      <p><strong>Platform:</strong> <%= @container.json['Platform'] %></p>
    </div>
  <% end %>
</div>

app/views/containers/stats.html.erb
<div class="ml-64 p-10">
  <div class="h-full flex flex-col justify-center items-start bg-white rounded-lg shadow-md p-6 mt-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-4">Container Stats</h2>
    <div class="space-y-3">
      <p><strong>Container ID:</strong> <span class="text-gray-600"><%= @container_stats.dig("id") %></span></p>
      <p><strong>Name:</strong> <span class="text-gray-600"><%= @container_stats.dig("name") %></span></p>
      <p><strong>CPU Usage:</strong> <span class="text-gray-600"><%= '%.2f' % ((@container_stats.dig("cpu_stats", "cpu_usage", "total_usage").to_f - @container_stats.dig("precpu_stats", "cpu_usage", "total_usage").to_f) / (@container_stats.dig("cpu_stats", "system_cpu_usage") - @container_stats.dig("precpu_stats", "system_cpu_usage")) * 100 * @container_stats.dig("cpu_stats", "online_cpus")) rescue 'N/A' %> %</span></p>
      <p><strong>Memory Usage / Limit:</strong> <span class="text-gray-600"><%= humanize_bytes(@container_stats.dig("memory_stats", "usage")) %> / <%= humanize_bytes(@container_stats.dig("memory_stats", "limit")) %></span></p>
      <p><strong>Memory %:</strong> <span class="text-gray-600"><%= '%.2f' % (@container_stats.dig("memory_stats", "usage").to_f / @container_stats.dig("memory_stats", "limit") * 100) rescue 'N/A' %> %</span></p>
      <p><strong>NET I/O:</strong> <span class="text-gray-600"><%= humanize_bytes(@container_stats.dig("networks", "eth0", "rx_bytes")) %> / <%= humanize_bytes(@container_stats.dig("networks", "eth0", "tx_bytes")) %></span></p>
      <p><strong>BLOCK I/O:</strong> <span class="text-gray-600">TBD</span></p>
      <p><strong>PIDS:</strong> <span class="text-gray-600"><%= @container_stats.dig("pids_stats", "current") %></span></p>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="ml-64 p-8">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
    <div class="bg-blue-500 text-white p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold">Containers</h2>
      <p><span class="text-3xl"><%= @info['Containers'] %></span> Total</p>
      <p><span class="text-3xl"><%= @info['ContainersRunning'] %></span> Active</p>
    </div>
    <div class="bg-green-500 text-white p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold">Images</h2>
      <p><span class="text-3xl"><%= @info['Images'] %></span> Total</p>
    </div>
    <div class="bg-red-500 text-white p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold">Networks</h2>
      <p><span class="text-3xl">N/A</span> Total</p>
    </div>
    <div class="bg-yellow-500 text-white p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold">Volumes</h2>
      <p><span class="text-3xl">N/A</span> Total</p>
    </div>
    </div>
    <div class="bg-purple-500 text-white p-4 rounded-lg shadow-md">
      <h2 class="text-xl font-bold">System Info</h2>
      <p><i class="fa-solid fa-microchip"></i> CPU: <span class="text-3xl"><%= @info['NCPU'] %></span></p>
      <p><i class="fa-solid fa-memory"></i> Memory: <span class="text-3xl"><%= (@info['MemTotal'].to_f / 2**30).round(2) %> GiB</span></p>
      <p><i class="fa-solid fa-laptop"></i> OS: <span class="text-xl"><%= @info['OperatingSystem'] %></span></p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to "/", class: "flex items-center space-x-3 rtl:space-x-reverse" do %>
      <%= image_tag 'container.png', class: "h-8", alt: "AC Logo" %>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Azeroth Containers</span>
    <% end %>
    <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Get started</button>
        <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!-- SVG for hamburger icon -->
        </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to 'Home', root_path, class: "block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500", aria: { current: "page" } %>
        </li>
        <li>
          <%= link_to 'Containers', containers_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <!-- Additional links -->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Azeroth Containers</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="bg-gray-900">
  <div class="flex">
    <%= render '/layouts/sidebar' %>
    <main class="flex-1">
      <%= yield %>
    </main>
  </div>
</body>
</html>